"""Explicit leading generator markers only; ordinary documentation is not evidence."""
import re

MARKERS=re.compile(r'^(?:DO NOT EDIT\b.*(?:automatically maintained|auto[- ]?generated|generated (?:by|from))|GENERATED (?:by|from)\b|<auto-generated\b)',re.I)

def generator_header(raw):
    text=raw.decode('utf-8').lstrip('\ufeff');signals=[];block=False
    for number,line in enumerate(text.splitlines()[:64],1):
        stripped=line.strip()
        if not stripped:continue
        if stripped.startswith('/*'):block=True
        if not (block or stripped.startswith(('//','#'))):break
        content=re.sub(r'^(?://|#|/\*+|\*)\s*','',stripped).rstrip('*/ ').strip()
        if MARKERS.search(content):signals.append({'line':number,'text':line,'classification':'GENERATED_EXPLICIT_HEADER'})
        if '*/' in stripped:block=False
    return signals
