import unittest
from scripts.code_analysis.classification import generator_header

class ClassificationTests(unittest.TestCase):
    def test_exact_generated_factory_and_css_headers(self):
        for raw in [b'// DO NOT EDIT - Automatically maintained by createStructurePrinterFactory.ts\nexport class X{}',b'/* license */\n// GENERATED by tooling/generate-css-data.js -- do not edit.\nconst x=1;',b'// <auto-generated />\nclass X{}']:
            self.assertEqual(len(generator_header(raw)),1)
    def test_incidental_documentation_and_literals_do_not_classify(self):
        for raw in [b'/// A simple source of information generated by Serilog itself\nclass X{}',b'/// result generated by visiting\nclass X{}',b'const x="// GENERATED by something";',b'function example(){}\n// GENERATED by documentation example']:
            self.assertEqual(generator_header(raw),[])
