namespace AssetBlock.Domain.Core.Constants;

/// <summary>
/// Centralized error codes for API responses. All constants UPPER_SNAKE_CASE, values prefixed with ERR_.
/// </summary>
public static class ErrorCodes
{
    public const string ERR_AUTH_INVALID_CREDENTIALS = "ERR_AUTH_INVALID_CREDENTIALS";
    public const string ERR_AUTH_TOKEN_EXPIRED = "ERR_AUTH_TOKEN_EXPIRED";
    public const string ERR_AUTH_TOKEN_INVALID = "ERR_AUTH_TOKEN_INVALID";
    public const string ERR_AUTH_USER_NOT_FOUND = "ERR_AUTH_USER_NOT_FOUND";
    public const string ERR_AUTH_EMAIL_ALREADY_EXISTS = "ERR_AUTH_EMAIL_ALREADY_EXISTS";
    public const string ERR_AUTH_CURRENT_PASSWORD_INVALID = "ERR_AUTH_CURRENT_PASSWORD_INVALID";
    public const string ERR_EMAIL_ACTION_INVALID_OR_EXPIRED = "ERR_EMAIL_ACTION_INVALID_OR_EXPIRED";
    public const string ERR_EMAIL_ACTION_COOLDOWN = "ERR_EMAIL_ACTION_COOLDOWN";
    public const string ERR_EMAIL_CHANGE_SAME_AS_CURRENT = "ERR_EMAIL_CHANGE_SAME_AS_CURRENT";
    public const string ERR_EMAIL_CHANGE_TARGET_TAKEN = "ERR_EMAIL_CHANGE_TARGET_TAKEN";
    public const string ERR_EMAIL_NOT_VERIFIED = "ERR_EMAIL_NOT_VERIFIED";

    public const string ERR_CATEGORY_NOT_FOUND = "ERR_CATEGORY_NOT_FOUND";
    public const string ERR_TAG_NOT_FOUND = "ERR_TAG_NOT_FOUND";
    public const string ERR_TAG_ALREADY_EXISTS = "ERR_TAG_ALREADY_EXISTS";
    public const string ERR_ASSET_TAG_ALREADY_EXISTS = "ERR_ASSET_TAG_ALREADY_EXISTS";
    public const string ERR_ASSET_TAG_NOT_FOUND = "ERR_ASSET_TAG_NOT_FOUND";
    public const string ERR_ASSET_NOT_FOUND = "ERR_ASSET_NOT_FOUND";
    public const string ERR_ASSET_UPLOAD_FAILED = "ERR_ASSET_UPLOAD_FAILED";
    public const string ERR_ASSET_VERSION_NOT_FOUND = "ERR_ASSET_VERSION_NOT_FOUND";
    public const string ERR_LICENSE_CODE_INVALID = "ERR_LICENSE_CODE_INVALID";

    public const string ERR_PURCHASE_NOT_FOUND = "ERR_PURCHASE_NOT_FOUND";
    public const string ERR_PURCHASE_ACCESS_DENIED = "ERR_PURCHASE_ACCESS_DENIED";
    public const string ERR_PAYMENT_FAILED = "ERR_PAYMENT_FAILED";
    public const string ERR_STRIPE_URLS_NOT_CONFIGURED = "ERR_STRIPE_URLS_NOT_CONFIGURED";
    public const string ERR_STRIPE_WEBHOOK_INVALID = "ERR_STRIPE_WEBHOOK_INVALID";
    public const string ERR_PAYMENT_WEBHOOK_MISMATCH = "ERR_PAYMENT_WEBHOOK_MISMATCH";

    // User / profile
    public const string ERR_USER_NOT_FOUND = "ERR_USER_NOT_FOUND";
    public const string ERR_USERNAME_ALREADY_EXISTS = "ERR_USERNAME_ALREADY_EXISTS";
    public const string ERR_SOCIAL_PLATFORM_NOT_FOUND = "ERR_SOCIAL_PLATFORM_NOT_FOUND";
    public const string ERR_DOWNLOAD_LIMIT_EXCEEDED = "ERR_DOWNLOAD_LIMIT_EXCEEDED";
    public const string ERR_CANNOT_PURCHASE_OWN_ASSET = "ERR_CANNOT_PURCHASE_OWN_ASSET";
    public const string ERR_ASSET_ALREADY_PURCHASED = "ERR_ASSET_ALREADY_PURCHASED";
    public const string ERR_CHECKOUT_ALREADY_PENDING = "ERR_CHECKOUT_ALREADY_PENDING";
    public const string ERR_CHECKOUT_ITEM_RESERVED = "ERR_CHECKOUT_ITEM_RESERVED";

    public const string ERR_COLLECTION_NOT_FOUND = "ERR_COLLECTION_NOT_FOUND";
    public const string ERR_COLLECTION_EMPTY = "ERR_COLLECTION_EMPTY";
    public const string ERR_COLLECTION_ASSET_INVALID = "ERR_COLLECTION_ASSET_INVALID";
    public const string ERR_COLLECTION_DUPLICATE_ASSET = "ERR_COLLECTION_DUPLICATE_ASSET";
    public const string ERR_COLLECTION_STATE_INVALID = "ERR_COLLECTION_STATE_INVALID";

    public const string ERR_BUNDLE_NOT_FOUND = "ERR_BUNDLE_NOT_FOUND";
    public const string ERR_BUNDLE_UNAVAILABLE = "ERR_BUNDLE_UNAVAILABLE";
    public const string ERR_BUNDLE_ASSET_COUNT_INVALID = "ERR_BUNDLE_ASSET_COUNT_INVALID";
    public const string ERR_BUNDLE_ASSET_INVALID = "ERR_BUNDLE_ASSET_INVALID";
    public const string ERR_BUNDLE_DUPLICATE_ASSET = "ERR_BUNDLE_DUPLICATE_ASSET";
    public const string ERR_BUNDLE_PRICE_INVALID = "ERR_BUNDLE_PRICE_INVALID";
    public const string ERR_CANNOT_PURCHASE_OWN_BUNDLE = "ERR_CANNOT_PURCHASE_OWN_BUNDLE";
    public const string ERR_BUNDLE_CONTAINS_OWNED_ASSET = "ERR_BUNDLE_CONTAINS_OWNED_ASSET";

    public const string ERR_CATEGORY_SLUG_EXISTS = "ERR_CATEGORY_SLUG_EXISTS";

    public const string ERR_REVIEW_ALREADY_EXISTS = "ERR_REVIEW_ALREADY_EXISTS";
    public const string ERR_REVIEW_TIME_WINDOW_EXPIRED = "ERR_REVIEW_TIME_WINDOW_EXPIRED";
    public const string ERR_ASSET_NOT_PURCHASED = "ERR_ASSET_NOT_PURCHASED";
    public const string ERR_REVIEW_NOT_FOUND = "ERR_REVIEW_NOT_FOUND";
    public const string ERR_CANNOT_REVIEW_OWN_ASSET = "ERR_CANNOT_REVIEW_OWN_ASSET";
    public const string ERR_REVIEW_CREATE_FAILED = "ERR_REVIEW_CREATE_FAILED";

    public const string ERR_FILE_REQUIRED = "ERR_FILE_REQUIRED";
    public const string ERR_FILE_TOO_LARGE = "ERR_FILE_TOO_LARGE";
    public const string ERR_FILE_EXTENSION_NOT_ALLOWED = "ERR_FILE_EXTENSION_NOT_ALLOWED";
    public const string ERR_ARCHIVE_REJECTED = "ERR_ARCHIVE_REJECTED";
    public const string ERR_NOT_FOUND = "ERR_NOT_FOUND";
    public const string ERR_FORBIDDEN = "ERR_FORBIDDEN";
    public const string ERR_BAD_REQUEST = "ERR_BAD_REQUEST";
    public const string ERR_CONFLICT = "ERR_CONFLICT";
    public const string ERR_INTERNAL = "ERR_INTERNAL";
    public const string ERR_VALIDATION_FAILED = "ERR_VALIDATION_FAILED";
    public const string ERR_RATE_LIMITED = "ERR_RATE_LIMITED";
    public const string ERR_SERVICE_UNAVAILABLE = "ERR_SERVICE_UNAVAILABLE";

    public const string ERR_NOTIFICATION_NOT_FOUND = "ERR_NOTIFICATION_NOT_FOUND";
    public const string ERR_NOTIFICATIONS_LIST_FAILED = "ERR_NOTIFICATIONS_LIST_FAILED";
    public const string ERR_NOTIFICATIONS_UNREAD_READ_AT_SORT = "ERR_NOTIFICATIONS_UNREAD_READ_AT_SORT";

    public const string ERR_PURCHASES_LIST_FAILED = "ERR_PURCHASES_LIST_FAILED";

    // Seller Analytics
    public const string ERR_ANALYTICS_INVALID_RANGE = "ERR_ANALYTICS_INVALID_RANGE";
    public const string ERR_ANALYTICS_INVALID_CURSOR = "ERR_ANALYTICS_INVALID_CURSOR";
    public const string ERR_ANALYTICS_INVALID_FILTER = "ERR_ANALYTICS_INVALID_FILTER";
    public const string ERR_ANALYTICS_EXPORT_TOO_LARGE = "ERR_ANALYTICS_EXPORT_TOO_LARGE";

    // Engagement telemetry
    public const string ERR_ANALYTICS_EVENT_INVALID = "ERR_ANALYTICS_EVENT_INVALID";
    public const string ERR_ANALYTICS_ATTRIBUTION_INVALID = "ERR_ANALYTICS_ATTRIBUTION_INVALID";
    public const string ERR_ANALYTICS_BFF_SIGNATURE_INVALID = "ERR_ANALYTICS_BFF_SIGNATURE_INVALID";
    public const string ERR_ANALYTICS_RATE_LIMIT_UNAVAILABLE = "ERR_ANALYTICS_RATE_LIMIT_UNAVAILABLE";

    public const string VERSION_NOT_FOUND = "VERSION_NOT_FOUND";
    public const string ARCHIVE_CORRUPT = "ARCHIVE_CORRUPT";
    public const string ARCHIVE_UNSEEKABLE = "ARCHIVE_UNSEEKABLE";
    public const string ARCHIVE_ENCRYPTED = "ARCHIVE_ENCRYPTED";
    public const string ARCHIVE_EMPTY_PATH = "ARCHIVE_EMPTY_PATH";
    public const string ARCHIVE_PATH_TOO_LONG = "ARCHIVE_PATH_TOO_LONG";
    public const string ARCHIVE_PATH_TOO_DEEP = "ARCHIVE_PATH_TOO_DEEP";
    public const string ARCHIVE_ABSOLUTE_PATH = "ARCHIVE_ABSOLUTE_PATH";
    public const string ARCHIVE_PATH_TRAVERSAL = "ARCHIVE_PATH_TRAVERSAL";
    public const string ARCHIVE_DUPLICATE_ENTRY = "ARCHIVE_DUPLICATE_ENTRY";
    public const string ARCHIVE_SYMLINK_NOT_ALLOWED = "ARCHIVE_SYMLINK_NOT_ALLOWED";
    public const string ARCHIVE_SPECIAL_ENTRY_NOT_ALLOWED = "ARCHIVE_SPECIAL_ENTRY_NOT_ALLOWED";
    public const string ARCHIVE_TOO_MANY_ENTRIES = "ARCHIVE_TOO_MANY_ENTRIES";
    public const string ARCHIVE_ENTRY_TOO_LARGE = "ARCHIVE_ENTRY_TOO_LARGE";
    public const string ARCHIVE_COMPRESSION_RATIO_EXCEEDED = "ARCHIVE_COMPRESSION_RATIO_EXCEEDED";
    public const string ARCHIVE_TOTAL_SIZE_EXCEEDED = "ARCHIVE_TOTAL_SIZE_EXCEEDED";
    public const string ARCHIVE_EMPTY = "ARCHIVE_EMPTY";
    public const string ARCHIVE_UNSAFE = "ARCHIVE_UNSAFE";
    public const string STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE";
    public const string STORAGE_IO_ERROR = "STORAGE_IO_ERROR";
    public const string LEASE_LOST = "LEASE_LOST";
    public const string LEASE_EXPIRED = "LEASE_EXPIRED";
    public const string MALWARE_DETECTED = "MALWARE_DETECTED";
    public const string SCANNER_UNAVAILABLE = "SCANNER_UNAVAILABLE";
    public const string SCANNER_ERROR = "SCANNER_ERROR";
    public const string SCANNER_LIMIT_EXCEEDED = "SCANNER_LIMIT_EXCEEDED";
    public const string MISSING_HANDLER = "MISSING_HANDLER";
    public const string INVALID_JOB_PAYLOAD = "INVALID_JOB_PAYLOAD";
    public const string INVALID_JOB_RESULT = "INVALID_JOB_RESULT";
    public const string WORKER_SHUTDOWN = "WORKER_SHUTDOWN";
    public const string PROCESSING_TIMEOUT = "PROCESSING_TIMEOUT";
    public const string PROCESSING_EXCEPTION = "PROCESSING_EXCEPTION";
    public const string AI_DISABLED = "AI_DISABLED";
    public const string AI_PROVIDER_UNAVAILABLE = "AI_PROVIDER_UNAVAILABLE";
    public const string AI_RATE_LIMITED = "AI_RATE_LIMITED";
    public const string AI_TIMEOUT = "AI_TIMEOUT";
    public const string AI_UNAUTHORIZED = "AI_UNAUTHORIZED";
    public const string AI_PAYMENT_REQUIRED = "AI_PAYMENT_REQUIRED";
    public const string AI_FORBIDDEN = "AI_FORBIDDEN";
    public const string AI_INVALID_REQUEST = "AI_INVALID_REQUEST";
    public const string AI_INVALID_RESPONSE = "AI_INVALID_RESPONSE";
    public const string AI_MODEL_NOT_ALLOWED = "AI_MODEL_NOT_ALLOWED";
    public const string AI_CATEGORY_NOT_ALLOWED = "AI_CATEGORY_NOT_ALLOWED";
    public const string AI_TAGS_NOT_ALLOWED = "AI_TAGS_NOT_ALLOWED";
    public const string AI_INPUT_TOO_LARGE = "AI_INPUT_TOO_LARGE";
    public const string AI_ERROR = "AI_ERROR";
    public const string AI_VERSION_NOT_READY = "AI_VERSION_NOT_READY";
    public const string AI_ARCHIVE_ANALYSIS_MISSING = "AI_ARCHIVE_ANALYSIS_MISSING";
    public const string AI_ALLOWLIST_OVERFLOW = "AI_ALLOWLIST_OVERFLOW";
}
